name: Genesis Project Setup

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the new project'
        required: true
      github_issue_url:
        description: 'GitHub issue URL or requirements'
        required: false
      tech_stack:
        description: 'Preferred technology stack'
        required: false
        default: 'auto-detect'

jobs:
  genesis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout workflow repository
      uses: actions/checkout@v4
      
    - name: Setup Claude Code
      run: |
        # Install Claude Code CLI
        curl -fsSL https://claude.ai/install.sh | sh
        
    - name: Run Genesis Workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        claude code --workflow genesis \
          --project-name "${{ github.event.inputs.project_name }}" \
          --requirements "${{ github.event.inputs.github_issue_url }}" \
          --tech-stack "${{ github.event.inputs.tech_stack }}"
        
    - name: Upload Project Structure
      uses: actions/upload-artifact@v4
      with:
        name: generated-project
        path: output/
        
    - name: Create Repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh repo create "${{ github.event.inputs.project_name }}" \
          --public \
          --description "Generated by Genesis Workflow" \
          --clone
          
    - name: Push Initial Structure
      run: |
        cd "${{ github.event.inputs.project_name }}"
        git add .
        git commit -m "🚀 Initial project structure generated by Genesis workflow

        🤖 Generated with [Claude Code](https://claude.ai/code)
        
        Co-Authored-By: Claude <noreply@anthropic.com>"
        git push origin main